import "@/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";

import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/react";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html
        className={`${GeistSans.className} antialiased motion-safe:scroll-smooth`}
        lang="en"
        suppressHydrationWarning
      >
        <body className="antialiased">
          <NextTopLoader color="#16a34a" height={4} showSpinner={false} />

          <TRPCReactProvider>{children}</TRPCReactProvider>

          <div className="lg:hidden">
            <Toaster richColors position="bottom-center" duration={5000} />
          </div>
          <div className="hidden lg:flex">
            <Toaster richColors position="top-center" duration={5000} />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
